/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Core: typeof import('./src/components/SceneCore/components/Core.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Intersection: typeof import('./src/components/Intersection/Intersection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Source: typeof import('./src/components/SceneCore/components/Source.vue')['default']
    Tool: typeof import('./src/components/SceneCore/tools/Tool.vue')['default']
  }
}
