export enum E_EVENT_SCENE {
  BOX_SELECTION = 'BOX_SELECTION', // 框选
  SCENE_OPERATION_STATUS = 'SCENE_OPERATION_STATUS',
  LINK_STATUS = 'LINK_STATUS', // 连线状态
  MOVE_COMPONENT = 'MOVE_COMPONENT', // 移动组件
}
