export enum E_EVENT_SCENE {
  BOX_SELECTION = 'BOX_SELECTION', // 框选
  SCENE_OPERATION_STATUS = 'SCENE_OPERATION_STATUS',
  LINK_STATUS = 'LINK_STATUS', // 连线状态
  MOVE_COMPONENT = 'MOVE_COMPONENT', // 移动组件
  MOVE_LINK = 'MOVE_LINK', // 移动连线
  MOUSE_DOWN_SCENE = 'CLEAR_SCENE', // 点击了场景，目前做了选中清除等功能
}
